config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount Shrine.presign_endpoint(:cache), at: "/s3/params"

  match "(*any)", to: redirect(subdomain: ""), via: :all, constraints: { subdomain: "www" }

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_for :users,
    path: "",
    path_names: { sign_in: "login", sign_out: "logout", sign_up: "signup" },
    skip: :omniauth_callbacks,
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  resources :pages, param: :slug, only: :show
  resources :news, only: [:index, :show]

  resource :profile, only: [:new, :create]

  resources :packages do
    collection do
      get "expected"
      get "warehouse"
      get "in_transit"
      get "arrived"
    end
  end

  get "contacts", to: "pages#contacts"
  get "stores", to: "pages#stores"
  get "find_tracking", to: "pages#find_tracking"
  get "turkey", to: "pages#turkey"
  get "us_address", to: "pages#us_address"

  namespace :admin do
    root "packages#index"
    resources :users, only: [:index, :edit, :update] do
      member do
        get "become"
      end
    end

    resources :packages do
      get "new_or_edit", on: :collection
      get "set_as_received", on: :collection
      get "cn23", on: :member
    end

    resources :shipments do
      get "pending_invoice", on: :collection
      member do
        get "invoice"
        get "list_cp71"
        get "invoice_register"
        patch "set_as_in_transit"
        patch "set_as_arrived"
      end
    end

    resources :pages, except: :show
    resources :news, except: :show

    resource :shipment_next_date, only: :update

    resources :autocomplete_package_item_descriptions, only: [:index, :create, :destroy]
    
    post "autocomplete_find_user", to: "autocomplete#find_user"
    post "autocomplete_first_name", to: "autocomplete#first_name"
    post "autocomplete_last_name", to: "autocomplete#last_name"
    post "autocomplete_package_description", to: "autocomplete#package_description"
  end

  root "pages#index"

  authenticate :user, ->(user) { user.super_admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/views/admin/pages/_form.html.erb
<%= simple_form_for [:admin, @page], defaults: { wrapper: false } do |f| %>
  <div class="form-group">
    <%= f.input :slug %>
  </div>

  <div class="form-group">
    <%= f.input :title %>
  </div>
  
  <%= f.input :content, as: :hidden %>
  <trix-editor input="page_content"></trix-editor>

  <div class="mt-3">
    <%= f.button :submit, class: "mr-1" %>
    <%= link_to t("cancel"), admin_pages_path, class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/admin/pages/_page.html.erb
<div class="card mb-2">
  <div class="card-body">
    <div class="d-flex">
      <h5 class="card-title mr-2"><%= page.title %></h5>
      <%= link_to edit_admin_page_path(page), class: "text-secondary mr-1" do %>
        <i class="far fa-edit"></i>
      <% end %>
      <%= link_to admin_page_path(page), class: "text-secondary", method: :delete, data: { confirm: t("confirmation") } do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    </div>
    <h6 class="card-subtitle text-muted">/<%= page.slug %></h6>
  </div>
</div>

app/views/admin/pages/edit.html.erb
<%= content_for :title do %>
  <%= t(".title") %>
<% end %>

<h2 class="mb-3"><%= t(".title") %></h2>
<%= render "form" %>

app/views/admin/pages/index.html.erb
<%= content_for :title do %>
  <%= t(".title") %>
<% end %>

<h2 class="mb-3"><%= t(".title") %></h2>
<%= link_to t(".add_page"), new_admin_page_path, class: "btn btn-primary" %>
<div class="my-4">
  <%= render @pages %>
</div>

app/views/admin/pages/new.html.erb
<%= content_for :title do %>
  <%= t(".title") %>
<% end %>

<h2 class="mb-3"><%= t(".title") %></h2>
<%= render "form" %>