config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount Shrine.presign_endpoint(:cache), at: "/s3/params"

  match "(*any)", to: redirect(subdomain: ""), via: :all, constraints: { subdomain: "www" }

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_for :users,
    path: "",
    path_names: { sign_in: "login", sign_out: "logout", sign_up: "signup" },
    skip: :omniauth_callbacks,
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  resources :pages, param: :slug, only: :show
  resources :news, only: [:index, :show]

  resource :profile, only: [:new, :create]

  resources :packages do
    collection do
      get "expected"
      get "warehouse"
      get "in_transit"
      get "arrived"
    end
  end

  get "contacts", to: "pages#contacts"
  get "stores", to: "pages#stores"
  get "find_tracking", to: "pages#find_tracking"
  get "turkey", to: "pages#turkey"
  get "us_address", to: "pages#us_address"

  namespace :admin do
    root "packages#index"
    resources :users, only: [:index, :edit, :update] do
      member do
        get "become"
      end
    end

    resources :packages do
      get "new_or_edit", on: :collection
      get "set_as_received", on: :collection
      get "cn23", on: :member
    end

    resources :shipments do
      get "pending_invoice", on: :collection
      member do
        get "invoice"
        get "list_cp71"
        get "invoice_register"
        patch "set_as_in_transit"
        patch "set_as_arrived"
      end
    end

    resources :pages, except: :show
    resources :news, except: :show

    resource :shipment_next_date, only: :update

    resources :autocomplete_package_item_descriptions, only: [:index, :create, :destroy]
    
    post "autocomplete_find_user", to: "autocomplete#find_user"
    post "autocomplete_first_name", to: "autocomplete#first_name"
    post "autocomplete_last_name", to: "autocomplete#last_name"
    post "autocomplete_package_description", to: "autocomplete#package_description"
  end

  root "pages#index"

  authenticate :user, ->(user) { user.super_admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/views/shared/_alerts_bootstrap.html.erb
<% if notice %>
  <div class="js-alert my-3 alert alert-primary alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="js-alert my-3 alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_alerts_new.html.erb
<% if notice %>
  <div class="js-alert bg-blue-lightest border border-blue-light text-blue-dark px-4 py-3 rounded mb-6" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="js-alert bg-red-lightest border border-red-light text-red-dark px-4 py-3 rounded mb-6" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer_tailwind.html.erb
<footer class="mb-12">
  <ul class="list-reset flex mb-4">
    <li class="mr-2"><%= link_to t("home"), root_path %></li>
    <li class="mr-2"><%= link_to t("navbar.services"), page_path(slug: "services") %></li>
    <li class="mr-2"><%= link_to t("navbar.about_us"), page_path(slug: "about-us") %></li>
    <li class="mr-2"><%= link_to t("navbar.pricing"), page_path(slug: "pricing") %></li>
    <li class="mr-2"><%= link_to t("navbar.terms"), page_path(slug: "terms-and-conditions") %></li>
    <li class="mr-2"><%= link_to t("navbar.prohibited_items"), page_path(slug: "prohibited-items") %></li>
    <li class="mr-2"><%= link_to t("navbar.working_hours"), page_path(slug: "working-hours") %></li>
    <li class="mr-2"><%= link_to t("navbar.news"), news_index_path %></li>
    <li class="mr-2"><%= link_to t("navbar.contact_us"), contacts_path %></li>
  </ul>

  <div class="mb-4">
    <%= render(ContactComponent.new(contact: SiteConfig.contact1)) %>,
    <%= render(ContactComponent.new(contact: SiteConfig.contact2)) %>
    <span class="ml-3">
      <a href="https://www.instagram.com/<%= SiteConfig.instagram %>" class="mr-1">
        <svg role="img" width="16" height="16" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 0C8.74 0 8.333.015 7.053.072 5.775.132 4.905.333 4.14.63c-.789.306-1.459.717-2.126 1.384S.935 3.35.63 4.14C.333 4.905.131 5.775.072 7.053.012 8.333 0 8.74 0 12s.015 3.667.072 4.947c.06 1.277.261 2.148.558 2.913.306.788.717 1.459 1.384 2.126.667.666 1.336 1.079 2.126 1.384.766.296 1.636.499 2.913.558C8.333 23.988 8.74 24 12 24s3.667-.015 4.947-.072c1.277-.06 2.148-.262 2.913-.558.788-.306 1.459-.718 2.126-1.384.666-.667 1.079-1.335 1.384-2.126.296-.765.499-1.636.558-2.913.06-1.28.072-1.687.072-4.947s-.015-3.667-.072-4.947c-.06-1.277-.262-2.149-.558-2.913-.306-.789-.718-1.459-1.384-2.126C21.319 1.347 20.651.935 19.86.63c-.765-.297-1.636-.499-2.913-.558C15.667.012 15.26 0 12 0zm0 2.16c3.203 0 3.585.016 4.85.071 1.17.055 1.805.249 2.227.415.562.217.96.477 1.382.896.419.42.679.819.896 1.381.164.422.36 1.057.413 2.227.057 1.266.07 1.646.07 4.85s-.015 3.585-.074 4.85c-.061 1.17-.256 1.805-.421 2.227-.224.562-.479.96-.899 1.382-.419.419-.824.679-1.38.896-.42.164-1.065.36-2.235.413-1.274.057-1.649.07-4.859.07-3.211 0-3.586-.015-4.859-.074-1.171-.061-1.816-.256-2.236-.421-.569-.224-.96-.479-1.379-.899-.421-.419-.69-.824-.9-1.38-.165-.42-.359-1.065-.42-2.235-.045-1.26-.061-1.649-.061-4.844 0-3.196.016-3.586.061-4.861.061-1.17.255-1.814.42-2.234.21-.57.479-.96.9-1.381.419-.419.81-.689 1.379-.898.42-.166 1.051-.361 2.221-.421 1.275-.045 1.65-.06 4.859-.06l.045.03zm0 3.678c-3.405 0-6.162 2.76-6.162 6.162 0 3.405 2.76 6.162 6.162 6.162 3.405 0 6.162-2.76 6.162-6.162 0-3.405-2.76-6.162-6.162-6.162zM12 16c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm7.846-10.405c0 .795-.646 1.44-1.44 1.44-.795 0-1.44-.646-1.44-1.44 0-.794.646-1.439 1.44-1.439.793-.001 1.44.645 1.44 1.439z"/></svg>
      </a>
      <a href="https://www.facebook.com/<%= SiteConfig.facebook %>">
        <svg role="img" width="16" height="16" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M23.9981 11.9991C23.9981 5.37216 18.626 0 11.9991 0C5.37216 0 0 5.37216 0 11.9991C0 17.9882 4.38789 22.9522 10.1242 23.8524V15.4676H7.07758V11.9991H10.1242V9.35553C10.1242 6.34826 11.9156 4.68714 14.6564 4.68714C15.9692 4.68714 17.3424 4.92149 17.3424 4.92149V7.87439H15.8294C14.3388 7.87439 13.8739 8.79933 13.8739 9.74824V11.9991H17.2018L16.6698 15.4676H13.8739V23.8524C19.6103 22.9522 23.9981 17.9882 23.9981 11.9991Z"/></svg>
      </a>
    </span>
  </div>
  
  <small class="text-sm">
    &copy; <%= Date.current.year %> <%= SiteConfig.site_name %>
  </small>
</footer>