config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount Shrine.presign_endpoint(:cache), at: "/s3/params"

  match "(*any)", to: redirect(subdomain: ""), via: :all, constraints: { subdomain: "www" }

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_for :users,
    path: "",
    path_names: { sign_in: "login", sign_out: "logout", sign_up: "signup" },
    skip: :omniauth_callbacks,
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  resources :pages, param: :slug, only: :show
  resources :news, only: [:index, :show]

  resource :profile, only: [:new, :create]

  resources :packages do
    collection do
      get "expected"
      get "warehouse"
      get "in_transit"
      get "arrived"
    end
  end

  get "contacts", to: "pages#contacts"
  get "stores", to: "pages#stores"
  get "find_tracking", to: "pages#find_tracking"
  get "turkey", to: "pages#turkey"
  get "us_address", to: "pages#us_address"

  namespace :admin do
    root "packages#index"
    resources :users, only: [:index, :edit, :update] do
      member do
        get "become"
      end
    end

    resources :packages do
      get "new_or_edit", on: :collection
      get "set_as_received", on: :collection
      get "cn23", on: :member
    end

    resources :shipments do
      get "pending_invoice", on: :collection
      member do
        get "invoice"
        get "list_cp71"
        get "invoice_register"
        patch "set_as_in_transit"
        patch "set_as_arrived"
      end
    end

    resources :pages, except: :show
    resources :news, except: :show

    resource :shipment_next_date, only: :update

    resources :autocomplete_package_item_descriptions, only: [:index, :create, :destroy]
    
    post "autocomplete_find_user", to: "autocomplete#find_user"
    post "autocomplete_first_name", to: "autocomplete#first_name"
    post "autocomplete_last_name", to: "autocomplete#last_name"
    post "autocomplete_package_description", to: "autocomplete#package_description"
  end

  root "pages#index"

  authenticate :user, ->(user) { user.super_admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  enum status: [ :preparing, :in_transit, :arrived ], _prefix: true

  has_many :packages, dependent: :destroy
  has_many :users, -> { distinct }, through: :packages
  has_many :guests, -> { distinct }, through: :packages

  validate :has_pending_packages, on: :create
  before_create :insert_packages

  private
    def has_pending_packages
      errors.add(:shipment_packages, "Need at least 1 package") if Package.pending.count == 0
    end

    def insert_packages
      self.packages << Package.pending
    end
end

app/controllers/admin/shipments_controller.rb
module Admin
  class ShipmentsController < AdminController
    require "ru_propisju"
    require "translit"

    before_action -> { @shipment = Shipment.find(params[:id]) }, only: [:set_as_in_transit, :set_as_arrived]

    def index
      @shipments = Shipment.order(created_at: :desc)
    end

    def create
      @shipment = Shipment.create
      if @shipment.save
        redirect_to admin_shipments_path, notice: t(".notice")
      else
        redirect_to admin_shipments_path, alert: t(".alert")
      end
    end

    def set_as_in_transit
      @shipment.status_in_transit!
      redirect_to admin_shipments_path, notice: t(".notice")
    end

    def set_as_arrived
      @shipment.status_arrived!
      redirect_to admin_shipments_path, notice: t(".notice")
    end

    def pending_invoice
      @packages = Package.pending
      filename = "Invoice (pending shipment) #{Date.current}.xlsx"
      respond_to do |format|
        format.xlsx {
          response.headers["Content-Disposition"] = "attachment; filename=" + filename
        }
      end
    end

    def invoice
      @packages = Shipment.find(params[:id]).packages
      filename = "Invoice #{Date.current}.xlsx"
      respond_to do |format|
        format.xlsx {
          response.headers["Content-Disposition"] = "attachment; filename=" + filename
        }
      end
    end

    def list_cp71
      @shipment = Shipment.find(params[:id])
      render layout: "print"
    end

    def invoice_register
      @shipment = Shipment.find(params[:id])
      @packages =
        @shipment.packages.includes(:guest, :profile)
        .group_by do |p|
          if p.user
            "#{Translit.convert(p.user.profile.first_name, :russian)} #{Translit.convert(p.user.profile.last_name, :russian)}"
          else
            "#{Translit.convert(p.guest.first_name, :russian)} #{Translit.convert(p.guest.last_name, :russian)}"
          end
        end
        .sort.to_h

      filename = "Invoice Register #{Date.current}.xlsx"
      respond_to do |format|
        format.xlsx {
          response.headers["Content-Disposition"] = "attachment; filename=" + filename
        }
      end
    end

    def update
      @shipment = Shipment.find(params[:id])
      if @shipment.update(shipment_params)
        redirect_to admin_shipments_path, notice: "Номер Air WayBill обновлен"
      else
        redirect_to admin_shipments_path, alert: "Error"
      end
    end

    private
      def shipment_params
        params.require(:shipment).permit(:air_waybill)
      end
  end
end

app/helpers/shipment_helper.rb
module ShipmentHelper
  def package_item_description_code(desc)
    desc = desc.downcase
    if ["сумки", "сумка", "bag"].any? { |w| desc.include?(w) }
      "4202210000"
    elsif ["перчатки", "gloves"].any? { |w| desc.include?(w) }
      "6116930000"
    elsif ["clothes", "clothing", "parka", "costume", "jeans", "shirt", "jacket", "tee", "t-shirt", "pants", "skirt", "hoodie", "одежда", "одежды", "парка", "джинсы", "штаны", "рубашк", "куртка", "футболка", "толстовка", "юбка"].any? { |w| desc.include?(w) }
      "6114"
    elsif ["shoes", "obuv", "boots", "sneakers", "loafers", "botinki", "sapogi", "обувь", "ботинки", "кроссовки", "туфли", "сапоги"].any? { |w| desc.include?(w) }
      "6404110000"
    elsif ["book", "книга", "книги"].any? { |w| desc.include?(w) }
      "4901"
    elsif ["toy", "toys", "игрушка", "игрушки"].any? { |w| desc.include?(w) }
      "950300"
    elsif ["лыжи", "snowboard"].any? { |w| desc.include?(w) }
      "9506"
    elsif ["hat", "beanie", "шляпа", "шапка"].any? { |w| desc.include?(w) }
      "650500"
    elsif ["watch", "chasy", "часы"].any? { |w| desc.include?(w) }
      "9101"
    elsif ["cosmetics", "clinique", "mask", "gel", "beauty", "cream", "face", "hidrogel", "hydrogel", "маска", "гель", "патчи для глаз", "косметика", "тушь", "помада", "тени"].any? { |w| desc.include?(w) }
      "3304"
    elsif ["earphones", "earbuds", "наушники"].any? { |w| desc.include?(w) }
      "8518309500"
    elsif ["shampoo", "шампунь"].any? { |w| desc.include?(w) }
      "3305"
    elsif ["зубная щетка"].any? { |w| desc.include?(w) }
      "3306"
    elsif ["coffee", "cofee", "кофе"].any? { |w| desc.include?(w) }
      "0901"
    elsif ["guitar", "piano", "гитара"].any? { |w| desc.include?(w) }
      "9202"
    elsif ["phone", "телефон"].any? { |w| desc.include?(w) }
      "8517120000"
    elsif ["laptop", "notebook", "macbook", "lenovo", "ноутбук"].any? { |w| desc.include?(w) }
      "8471300000"
    elsif ["auto-parts", "autoparts", "auto parts", "parts", "car", "авто", "запчасти"].any? { |w| desc.include?(w) }
      "8708999709"
    elsif ["ковер", "ковёр"].any? { |w| desc.include?(w) }
      "5702100000"
    elsif ["glasses", "sunglasses", "очки"].any? { |w| desc.include?(w) }
      "9004109100"
    elsif ["socks", "носки"].any? { |w| desc.include?(w) }
      "6115950000"
    elsif ["bra", "panties", "lingerie", "бюстгальтер"].any? { |w| desc.include?(w) }
      "6108910000"
    elsif ["chair", "table", "стол", "стул", "полка", "тумбочка"].any? { |w| desc.include?(w) }
      "9403601009"
    elsif ["vitamin", "vitamins", "bady", "бады", "витамины", "now foods"].any? { |w| desc.include?(w) }
      "300450000"
    elsif ["кабель", "ram", "hdd", "ssd", "intel", "motherboard", "ethernet", "память", "mikrotik", "процессор"].any? { |w| desc.include?(w) }
      "8473302008"
    elsif ["screen", "защитное стекло", "case"].any? { |w| desc.include?(w) }
      "3926909709"
    elsif ["pencil", "pen", "penal", "paper", "stapler", "карандаш"].any? { |w| desc.include?(w) }
      "8305900000"
    elsif ["accessories", "accesories", "acsesuar", "stickers", "аксессуары"].any? { |w| desc.include?(w) }
      "96"
    end
  end
end

app/views/admin/shipments/_shipment.html.erb
<% if shipment.status_arrived? %>
  <tr>
<% else %>
  <tr style="background: #fffbdd">
<% end %>
  <th class="text-nowrap align-middle" scope="row">
    <%= shipment.created_at.strftime("%d-%m-%Y") %>
    <small class="text-muted"><%= shipment.created_at.strftime("%T") %></small>
  </th>
  <td class="text-nowrap align-middle"><%= shipment.packages.size %></td>
  <td class="text-nowrap align-middle"><strong><%= shipment.packages.sum(:weight) %> <%= t("weight_kg") %></strong></td>
  <td class="text-nowrap align-middle">
    <% if shipment.status_arrived? %>
      В Бишкеке
    <% else %>
      <div class="input-group">
        <input type="text" class="form-control form-control-sm" style="max-width: 180px" readonly value="<%= t("activerecord.attributes.shipment.status.#{shipment.status}") %>">
        <div class="input-group-append">
          <button type="button" class="btn btn-sm btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu">
            <%= link_to t("activerecord.attributes.shipment.status.in_transit"), set_as_in_transit_admin_shipment_path(shipment), method: :patch, class: "dropdown-item" %>
            <%= link_to t("activerecord.attributes.shipment.status.arrived"), set_as_arrived_admin_shipment_path(shipment), method: :patch, class: "dropdown-item" %>
          </div>
        </div>
      </div>
    <% end %>
  </td>
  <td class="text-nowrap align-middle">
    <%= link_to "Инвойс", invoice_admin_shipment_path(format: :xlsx, id: shipment), 'data-turbolinks': "false", class: "btn btn-sm btn-outline-primary mr-1" %>
    <%= link_to "CP-71", list_cp71_admin_shipment_path(shipment), 'data-turbolinks': "false", target: "_blank", class: "btn btn-sm btn-outline-primary mr-1" %>
    <%= link_to "Реестр грузов", invoice_register_admin_shipment_path(format: :xlsx, id: shipment), 'data-turbolinks': "false", class: "btn btn-sm btn-outline-primary" %>
  </td>
  <td class="text-nowrap align-middle">
    <%= simple_form_for [:admin, shipment] do |f| %>
      <%= f.input :air_waybill, label: false, input_html: { class: "form-control-sm" } %>
    <% end %>
  </td>
</tr>

app/views/admin/shipments/index.html.erb
<%= content_for :title do %>
  <%= t(".title") %>
<% end %>

<h2 class="mb-3"><%= t(".title") %></h2>
<% if current_user.super_admin? %>
  <%= form_with url: admin_shipments_path do |f| %>
    <div class="border rounded-sm col-md-4 p-3 shadow-sm">
      <div class="form-group row">
        <%= f.label :pending_packages, t(".packages_qty"), class: "col-6 col-form-label" %>
        <div class="col-6">
          <%= f.text_field :pending_packages, value: Package.pending.count, class: "form-control", readonly: true %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :pending_weight, t(".weight_total"), class: "col-6 col-form-label" %>
        <div class="col-6">
          <%= f.text_field :pending_weight, value: "#{Package.pending_weight} #{t("weight_kg")}", class: "form-control", readonly: true %>
        </div>
      </div>
      <div class="text-right">
        <%= f.submit t(".create"), class: "btn btn-primary" %>
        <%= link_to t(".invoice"), pending_invoice_admin_shipments_path(format: :xlsx), class: "ml-2 btn btn-outline-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

<div class="my-4 table-responsive">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col" class="align-middle"><%= t(".date_of_shipment") %></th>
        <th scope="col" class="align-middle" style="max-width: 100px"><%= t(".packages_qty") %></th>
        <th scope="col" class="align-middle"><%= t(".weight_total") %></th>
        <th scope="col" class="align-middle"><%= t(".status") %></th>
        <th scope="col" class="align-middle"><%= t(".documents") %></th>
        <th scope="col" class="align-middle">Air WayBill</th>
      </tr>
    </thead>
    <tbody>
      <%= render @shipments %>
    </tbody>
  </table>
</div>

app/views/admin/shipments/list_cp71.html.erb
<%= 
  render partial: "cp71",
  collection: @shipment.users, as: :owner,
  locals: { shipment: @shipment }
%>

<%= 
  render partial: "cp71",
  collection: @shipment.guests, as: :owner,
  locals: { shipment: @shipment }
%>