config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount Shrine.presign_endpoint(:cache), at: "/s3/params"

  match "(*any)", to: redirect(subdomain: ""), via: :all, constraints: { subdomain: "www" }

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_for :users,
    path: "",
    path_names: { sign_in: "login", sign_out: "logout", sign_up: "signup" },
    skip: :omniauth_callbacks,
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  resources :pages, param: :slug, only: :show
  resources :news, only: [:index, :show]

  resource :profile, only: [:new, :create]

  resources :packages do
    collection do
      get "expected"
      get "warehouse"
      get "in_transit"
      get "arrived"
    end
  end

  get "contacts", to: "pages#contacts"
  get "stores", to: "pages#stores"
  get "find_tracking", to: "pages#find_tracking"
  get "turkey", to: "pages#turkey"
  get "us_address", to: "pages#us_address"

  namespace :admin do
    root "packages#index"
    resources :users, only: [:index, :edit, :update] do
      member do
        get "become"
      end
    end

    resources :packages do
      get "new_or_edit", on: :collection
      get "set_as_received", on: :collection
      get "cn23", on: :member
    end

    resources :shipments do
      get "pending_invoice", on: :collection
      member do
        get "invoice"
        get "list_cp71"
        get "invoice_register"
        patch "set_as_in_transit"
        patch "set_as_arrived"
      end
    end

    resources :pages, except: :show
    resources :news, except: :show

    resource :shipment_next_date, only: :update

    resources :autocomplete_package_item_descriptions, only: [:index, :create, :destroy]
    
    post "autocomplete_find_user", to: "autocomplete#find_user"
    post "autocomplete_first_name", to: "autocomplete#first_name"
    post "autocomplete_last_name", to: "autocomplete#last_name"
    post "autocomplete_package_description", to: "autocomplete#package_description"
  end

  root "pages#index"

  authenticate :user, ->(user) { user.super_admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch::Model

  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :lockable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
  has_many :packages, dependent: :destroy
  has_many :shipments, through: :packages

  pg_search_scope :search_by_name_and_email,
    against: { email: "C" },
    associated_against: {
      profile: { first_name: "B", last_name: "A", phone: "C" }
    },
    using: {
      tsearch: { prefix: true }
    }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  # Auto remember user on Login
  def remember_me
    true
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    include Pagy::Backend

    def index
      @last_week = 7.days.ago.beginning_of_day..Time.current
      @last_month = 1.month.ago.beginning_of_day..Time.current
      @last_three_months = 3.months.ago.beginning_of_day..Time.current

      @signedup_last_week = User.where(created_at: @last_week).count
      @signedup_last_week_profile = User.includes(:profile)
                                         .where(created_at: @last_week)
                                         .where.not(profiles: {id: nil}).count

      @signedup_last_month = User.where(created_at: @last_month).count
      @signedup_last_month_profile = User.includes(:profile)
                                          .where(created_at: @last_month)
                                          .where.not(profiles: {id: nil}).count

      @signedup_last_three_months = User.where(created_at: @last_three_months).count
      @signedup_last_three_months_profile = User.includes(:profile)
                                                 .where(created_at: @last_three_months)
                                                 .where.not(profiles: {id: nil}).count


      if params[:search] && !params[:search].blank?
        @users_total = User.includes(:profile).search_by_name_and_email(params[:search])
        @pagy, @users = pagy(@users_total)
      elsif params[:show_admins]
        @users_total = User.includes(:profile).where("admin = true OR super_admin = true")
        @pagy, @users = pagy(@users_total)
      else
        @users_total = User.includes(:profile).where.not(profiles: {id: nil}).order("profiles.created_at desc")
        @pagy, @users = pagy(@users_total)
      end
    end

    def become
      return unless current_user.super_admin?
      sign_in(:user, User.find(params[:id]))
      redirect_to root_url
    end

    def edit
      user = User.find(params[:id])
      @profile = user.profile
    end

    def update
      user = User.find(params[:id])
      @profile = user.profile
      if @profile.update(profile_params)
        redirect_to edit_admin_user_path, notice: "Профиль ##{user.id} обновлен"
      else
        render :edit
      end
    end

    private
      def profile_params
        params.require(:profile).permit(
          :first_name,
          :last_name,
          :phone,
          :address,
          :city,
          passport_photos_attributes: [:id, :_destroy, :image]
        )
      end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "Google"
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/views/admin/users/_registrations.html.erb
<div class="card">
  <div class="card-header">
    <h6 class="mb-0"><%= t(".signed_up_users") %></h6>
  </div>

  <ul class="list-group list-group-flush">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= t(".signed_up_last_week") %>
      <div>
        <span class="badge badge-light">
          <%= @signedup_last_week %>
        </span>
        <span class="badge badge-light text-success">
          <i class="fas fa-passport"></i>
          <%= @signedup_last_week_profile %>
        </span>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= t(".signed_up_last_month") %>
      <div>
        <span class="badge badge-light">
          <%= @signedup_last_month %>
        </span>
        <span class="badge badge-light text-success">
          <i class="fas fa-passport"></i>
          <%= @signedup_last_month_profile %>
        </span>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= t(".signed_up_last_three_months") %>
      <div>
        <span class="badge badge-light">
          <%= @signedup_last_three_months %>
        </span>
        <span class="badge badge-light text-success">
          <i class="fas fa-passport"></i>
          <%= @signedup_last_three_months_profile %>
        </span>
      </div>
    </li>
  </ul>
</div>

app/views/admin/users/_user.html.erb
<div class="card card-body mb-2">
  <h5 class="card-title">
    <%= user.profile&.first_name %>
    <%= user.profile&.last_name %>
    <%= link_to "edit", edit_admin_user_path(user), target: :blank %>
    <small class="text-muted">
      #<%= user.id %> &nbsp;
      signed up at <%= user.created_at.to_s(:long) %>
    </small>
    <% if user.admin? || user.super_admin? %>
      <i class="fas fa-star text-warning"></i>
    <% end %>
  </h5>
  <h6 class="card-subtitle mb-2 text-muted"><%= user.email %></h6>
  
  <p class="card-text">
    <i class="fas fa-phone-alt text-muted"></i>
    <%= user.profile&.phone %>

    <i class="ml-3 fas fa-map text-muted mr-1"></i>
    <%= user.profile&.address %>,
    <%= user.profile&.city %>

    <span class="ml-2">
      <% user.profile&.passport_photos&.each do |photo| %>
        <%= link_to photo.image_url, target: :blank do %>
          <i class="fas fa-image text-muted"></i>
          passport photo
        <% end %>
      <% end %>
    </span>

    <% if current_user.super_admin? %>
      <span class="ml-3">
        <%= link_to "become", become_admin_user_path(id: user.id), 'data-turbolinks': false %>
      </span>
    <% end %>
  </p>
</div>

app/views/admin/users/edit.html.erb
<%= simple_form_for @profile, url: admin_user_path do |f| %>
  <div class="form-group">
    <%= f.input :first_name, label: false, placeholder: "Имя" %>
  </div>

  <div class="form-group">
    <%= f.input :last_name, label: false, placeholder: "Фамилия" %>
  </div>

  <h4>Фото паспорта</h4>
  <%= render(FileUploadComponent.new(
    form: f,
    model_name: "profile",
    model_instance: @profile,
    nested_attributes_name: "passport_photos",
    max_files: 5,
    display_previews_and_destroy: true
  )) %>

  <%= f.button :submit, "Обновить профиль пользователя", class: "mt-3 btn-block" %>
<% end %>

app/views/admin/users/index.html.erb
<%= content_for :title do %>
  <%= t(".title") %>
<% end %>

<div class="d-flex align-items-center mb-3">
  <h2 class="mr-2"><%= t(".title") %></h2>
  <h4>
    <span class="mr-1 badge badge-font-500 badge-pill badge-primary">
      <%= @users_total.count %>
    </span>
  </h4>
</div>

<div class="row">
  <div class="col-md-9">
    <div class="row">
      <div class="col-md-6">
        <%= form_tag admin_users_path, method: :get do %>
          <div class="input-group">
            <%= text_field_tag "search", params[:search], placeholder: t(".search_placeholder"), class: "form-control" %>
            <div class="input-group-append">
              <%= submit_tag t(".search"), class: "btn btn-outline-secondary" %>
            </div>
          </div>
        <% end %>
        <%= form_tag admin_users_path, method: :get do %>
          <div class="form-group form-check pl-0 mt-2 mb-0">
            <%= check_box_tag :show_admins, "yes", params[:show_admins] == "yes", onclick: "this.form.submit()" %>
            <label class="form-check-label" for="show_admins"><%= t(".filter_admins") %></label>
          </div>
        <% end %>
      </div>
    </div>

    <div class="my-4">
      <%= render @users %>
    </div>
    <%== pagy_nav(@pagy) %>
  </div>

  <div class="col-md-3 mt-4 mt-md-0">
    <%= render partial: "registrations" %>
  </div>
</div>